# Generated by Django 5.0.4 on 2024-04-11 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_recipe_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
